name: Canary Release
on:
  issue_comment:
    types: [created]

jobs:
  canary-release:
    name: canary-release
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'issue_comment' && startsWith(github.event.comment.body, '/canary-release')
    steps:
      - name: get pr information
        uses: actions/github-script@v6
        id: pr
        with:
          script: |
            const request = {
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            }
            console.log(`Getting PR #${request.pull_number} from ${request.owner}/${request.repo}`)
            try {
              const result = await octokit.pulls.get(request)
              console.log(`Got PR: ${JSON.stringify(result.data)}`)
              return result.data
            } catch (err) {
              core.setFailed(`Request failed with error ${err}`)
            }
      - name: checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ fromJSON(steps.pr.outputs.result).head.ref }}
          repository: ${{ fromJSON(steps.pr.outputs.result).head.repo.full_name }}
          fetch-depth: 0
      - name: setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          registry-url: 'https://npm.pkg.github.com'
          scope: '@Masaki-Yamanaka'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: install
        run: yarn
      - name: Publish
        run: yarn lerna publish --canary --preid next --dist-tag next --force-publish='*' --no-push --no-git-tag-version --yes --registry=https://npm.pkg.github.com
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GH_TOKEN }}
      - uses: actions/github-scripts@v6
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          script: |
            octokit.issues.createComment({
              issue_number: github.context.issue.number,
              owner: github.context.repo.owner,
              repo: github.context.repo.repo,
              body: '🎉 Canary Release. You can install canary version via npm install package@next'
            })
